window.Modernizr=function(h,d,m){function p(){g.input=function(a){for(var b=0,f=a.length;b<f;b++)z[a[b]]=!!(a[b]in k);return z}("autocomplete,autofocus,list,placeholder,max,min,multiple,pattern,required,step".split(","));g.inputtypes=function(a){for(var b=0,f,c,e,g=a.length;b<g;b++)k.setAttribute("type",c=a[b]),(f="text"!==k.type)&&(k.value=s,k.style.cssText="position:absolute;visibility:hidden;",/^range$/.test(c)&&k.style.WebkitAppearance!==m?(j.appendChild(k),e=d.defaultView,f=e.getComputedStyle&&
"textfield"!==e.getComputedStyle(k,null).WebkitAppearance&&0!==k.offsetHeight,j.removeChild(k)):/^(search|tel)$/.test(c)||(/^(url|email)$/.test(c)?f=k.checkValidity&&!1===k.checkValidity():/^color$/.test(c)?(j.appendChild(k),f=k.value!=s,j.removeChild(k)):f=k.value!=s)),A[a[b]]=!!f;return A}("search,tel,url,email,datetime,date,month,week,time,datetime-local,number,range,color".split(","))}function l(a,b){var f=a.charAt(0).toUpperCase()+a.substr(1),f=(a+" "+t.join(f+" ")+f).split(" ");return!!e(f,
b)}function e(a,b){for(var f in a)if(i[a[f]]!==m&&(!b||b(a[f],u)))return!0}function n(a,b){return typeof a===b}var g={},j=d.documentElement,B=d.head||d.getElementsByTagName("head")[0],u=d.createElement("modernizr"),i=u.style,k=d.createElement("input"),s=":)",C=Object.prototype.toString,o=",-webkit-,-moz-,-o-,-ms-,-khtml-".split(","),t=["Webkit","Moz","O","ms","Khtml"],c={},A={},z={},D=[],r,E=function(a){var b=d.createElement("style"),f=d.createElement("div");b.textContent=a+"{#modernizr{height:3px}}";
B.appendChild(b);f.id="modernizr";j.appendChild(f);a=3===f.offsetHeight;b.parentNode.removeChild(b);f.parentNode.removeChild(f);return!!a},v=function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,f){var f=f||d.createElement(a[b]||"div"),c=(b="on"+b)in f;c||(f.setAttribute||(f=d.createElement("div")),f.setAttribute&&f.removeAttribute&&(f.setAttribute(b,""),c=n(f[b],"function"),n(f[b],m)||(f[b]=m),f.removeAttribute(b)));return c}}(),
w={}.hasOwnProperty,x;n(w,m)||n(w.call,m)?x=function(a,b){return b in a&&n(a.constructor.prototype[b],m)}:x=function(a,b){return w.call(a,b)};c.flexbox=function(){var a=d.createElement("div"),b=d.createElement("div"),c;c="display:";a.style.cssText=(c+o.join("box;"+c)).slice(0,-c.length)+"width:42px;padding:0;";b.style.cssText=o.join("box-flex:1;")+"width:10px;";a.appendChild(b);j.appendChild(a);c=42===b.offsetWidth;a.removeChild(b);j.removeChild(a);return c};c.canvas=function(){var a=d.createElement("canvas");
return a.getContext&&a.getContext("2d")};c.canvastext=function(){return g.canvas&&n(d.createElement("canvas").getContext("2d").fillText,"function")};c.webgl=function(){return!!h.WebGLRenderingContext};c.touch=function(){return"ontouchstart"in h||E("@media ("+o.join("touch-enabled),(")+"modernizr)")};c.geolocation=function(){return!!navigator.geolocation};c.postmessage=function(){return!!h.postMessage};c.websqldatabase=function(){return!!h.openDatabase};c.indexedDB=function(){for(var a=-1,b=t.length;++a<
b;){var c=t[a].toLowerCase();if(h[c+"_indexedDB"]||h[c+"IndexedDB"])return!0}return!1};c.hashchange=function(){return v("hashchange",h)&&(d.documentMode===m||7<d.documentMode)};c.history=function(){return!(!h.history||!history.pushState)};c.draganddrop=function(){return v("dragstart")&&v("drop")};c.websockets=function(){return"WebSocket"in h};c.rgba=function(){i.cssText="background-color:rgba(150,255,150,.5)";return-1!==(""+i.backgroundColor).indexOf("rgba")};c.hsla=function(){i.cssText="background-color:hsla(120,40%,100%,.5)";
return-1!==(""+i.backgroundColor).indexOf("rgba")||-1!==(""+i.backgroundColor).indexOf("hsla")};c.multiplebgs=function(){i.cssText="background:url(//:),url(//:),red url(//:)";return/(url\s*\(.*?){3}/.test(i.background)};c.backgroundsize=function(){return l("backgroundSize")};c.borderimage=function(){return l("borderImage")};c.borderradius=function(){return l("borderRadius","",function(a){return-1!==(""+a).indexOf("orderRadius")})};c.boxshadow=function(){return l("boxShadow")};c.textshadow=function(){return""===
d.createElement("div").style.textShadow};c.opacity=function(){var a=o.join("opacity:.55;")+"";i.cssText=a;return/^0.55$/.test(i.opacity)};c.cssanimations=function(){return l("animationName")};c.csscolumns=function(){return l("columnCount")};c.cssgradients=function(){var a=("background-image:"+o.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+o.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,-17);i.cssText=a;return-1!==(""+i.backgroundImage).indexOf("gradient")};
c.cssreflections=function(){return l("boxReflect")};c.csstransforms=function(){return!!e(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};c.csstransforms3d=function(){var a=!!e(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);a&&"webkitPerspective"in j.style&&(a=E("@media ("+o.join("transform-3d),(")+"modernizr)"));return a};c.csstransitions=function(){return l("transitionProperty")};c.fontface=function(){var a,b,c=B||
j,e=d.createElement("style");b=d.implementation||{hasFeature:function(){return!1}};e.type="text/css";c.insertBefore(e,c.firstChild);a=e.sheet||e.styleSheet;b=(b.hasFeature("CSS2","")?function(b){if(!a||!b)return!1;var c=!1;try{a.insertRule(b,0),c=/src/i.test(a.cssRules[0].cssText),a.deleteRule(a.cssRules.length-1)}catch(d){}return c}:function(b){if(!a||!b)return!1;a.cssText=b;return 0!==a.cssText.length&&/src/i.test(a.cssText)&&0===a.cssText.replace(/\r+|\n+/g,"").indexOf(b.split(" ")[0])})('@font-face { font-family: "font"; src: url(data:,); }');
c.removeChild(e);return b};c.video=function(){var a=d.createElement("video"),b=!!a.canPlayType;b&&(b=new Boolean(b),b.ogg=a.canPlayType('video/ogg; codecs="theora"'),b.h264=a.canPlayType('video/mp4; codecs="avc1.42E01E"')||a.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"'),b.webm=a.canPlayType('video/webm; codecs="vp8, vorbis"'));return b};c.audio=function(){var a=d.createElement("audio"),b=!!a.canPlayType;b&&(b=new Boolean(b),b.ogg=a.canPlayType('audio/ogg; codecs="vorbis"'),b.mp3=a.canPlayType("audio/mpeg;"),
b.wav=a.canPlayType('audio/wav; codecs="1"'),b.m4a=a.canPlayType("audio/x-m4a;")||a.canPlayType("audio/aac;"));return b};c.localstorage=function(){try{return!!localStorage.getItem}catch(a){return!1}};c.sessionstorage=function(){try{return!!sessionStorage.getItem}catch(a){return!1}};c.webWorkers=function(){return!!h.Worker};c.applicationcache=function(){return!!h.applicationCache};c.svg=function(){return!!d.createElementNS&&!!d.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect};c.inlinesvg=
function(){var a=d.createElement("div");a.innerHTML="<svg/>";return"http://www.w3.org/2000/svg"==(a.firstChild&&a.firstChild.namespaceURI)};c.smil=function(){return!!d.createElementNS&&/SVG/.test(C.call(d.createElementNS("http://www.w3.org/2000/svg","animate")))};c.svgclippaths=function(){return!!d.createElementNS&&/SVG/.test(C.call(d.createElementNS("http://www.w3.org/2000/svg","clipPath")))};for(var y in c)x(c,y)&&(r=y.toLowerCase(),g[r]=c[y](),D.push((g[r]?"":"no-")+r));g.input||p();g.crosswindowmessaging=
g.postmessage;g.historymanagement=g.history;g.addTest=function(a,b){a=a.toLowerCase();if(!g[a])return b=!!b(),j.className+=" "+(b?"":"no-")+a,g[a]=b,g};i.cssText="";u=k=null;h.attachEvent&&function(){var a=d.createElement("div");a.innerHTML="<elem></elem>";return 1!==a.childNodes.length}()&&function(a,b){function c(a,b){for(var d=-1,e=a.length,g,m=[];++d<e;)g=a[d],"screen"!=(b=g.media||b)&&m.push(c(g.imports,b),g.cssText);return m.join("")}function d(a){for(var b=-1;++b<g;)a.createElement(e[b])}var e=
"abbr,article,aside,audio,canvas,details,figcaption,figure,footer,header,hgroup,mark,meter,nav,output,progress,section,summary,time,video".split(","),g=e.length,m=RegExp("(^|\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)","gi"),h=RegExp("<(/*)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)","gi"),k=RegExp("(^|[^\\n]*?\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)([^\\n]*)({[\\n\\w\\W]*?})",
"gi"),j=b.createDocumentFragment(),l=b.documentElement,i=l.firstChild,p=b.createElement("body"),n=b.createElement("style"),o;d(b);d(j);i.insertBefore(n,i.firstChild);n.media="print";a.attachEvent("onbeforeprint",function(){var a=-1,d=c(b.styleSheets,"all"),i=[],q;for(o=o||b.body;null!=(q=k.exec(d));)i.push((q[1]+q[2]+q[3]).replace(m,"$1.iepp_$2")+q[4]);for(n.styleSheet.cssText=i.join("\n");++a<g;){d=b.getElementsByTagName(e[a]);i=d.length;for(q=-1;++q<i;)0>d[q].className.indexOf("iepp_")&&(d[q].className+=
" iepp_"+e[a])}j.appendChild(o);l.appendChild(p);p.className=o.className;p.innerHTML=o.innerHTML.replace(h,"<$1font")});a.attachEvent("onafterprint",function(){p.innerHTML="";l.removeChild(p);l.appendChild(o);n.styleSheet.cssText=""})}(h,d);g._enableHTML5=!0;g._version="1.7";j.className=j.className.replace(/\bno-js\b/,"")+" js "+D.join(" ");return g}(this,this.document);Modernizr.addTest("ipad",function(){return!!navigator.userAgent.match(/iPad/i)});Modernizr.addTest("iphone",function(){return!!navigator.userAgent.match(/iPhone/i)});
Modernizr.addTest("ipod",function(){return!!navigator.userAgent.match(/iPod/i)});Modernizr.addTest("appleios",function(){return Modernizr.ipad||Modernizr.ipod||Modernizr.iphone});
(function(h,d){h.addTest("positionfixed",function(){var d=document.createElement("div"),h=d.cloneNode(!1),l=!1,e;if(!(e=document.body))l=!0,e=document.documentElement.appendChild(document.createElement("body"));var n=e.style.cssText;e.style.cssText="padding:0;margin:0";d.style.cssText="position:fixed;top:42px";e.appendChild(d);e.appendChild(h);var g=d.offsetTop!==h.offsetTop;e.removeChild(d);e.removeChild(h);e.style.cssText=n;l&&document.documentElement.removeChild(e);return g});h.addTest("iospositionfixed",
function(){var m=document.createElement("div"),p,l=!1,e;if(!(e=document.body))l=!0,e=document.documentElement.appendChild(document.createElement("body"));if("function"===typeof document.body.scrollIntoViewIfNeeded){var n=e.style.cssText,g=d.pageYOffset;e.appendChild(m);m.style.cssText="position:fixed;top:0px;height:10px;";e.style.height="3000px";var j=function(){void 0===p&&(m.scrollIntoViewIfNeeded(),p=20===d.pageYOffset?!0:!1);d.removeEventListener("scroll",j,!1)};d.addEventListener("scroll",20,
!1);d.setTimeout(j,20);d.scrollTo(0,20);j();e.removeChild(m);e.style.cssText=n;d.scrollTo(0,g)}else p=h.positionfixed;l&&document.documentElement.removeChild(e);return p})})(Modernizr,window);
//@ sourceMappingURL=modernizr.js.map
